package toncenter

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"math/big"

	"github.com/xssnick/tonutils-go/address"
	"github.com/xssnick/tonutils-go/tvm/cell"
)

// maxInt64BigInt is used for overflow checking when converting uint256 to int64
var maxInt64BigInt = big.NewInt(math.MaxInt64)

// safeUint256ToInt64 safely converts a big.Int (uint256) to int64 with overflow check.
// Returns error if the value exceeds MaxInt64.
func safeUint256ToInt64(value *big.Int, fieldName string) (int64, error) {
	if value.Cmp(maxInt64BigInt) > 0 {
		return 0, fmt.Errorf("%s value %s exceeds int64 max (%d)", fieldName, value.String(), math.MaxInt64)
	}
	if value.Sign() < 0 {
		return 0, fmt.Errorf("%s value %s is negative", fieldName, value.String())
	}
	return value.Int64(), nil
}

// Message opcodes for game contract notifications.
// These are auto-generated by Tact compiler from PODGame_Game.abi.
// Header values from ABI: "GameInitializedNotify": {"header": 3945341079}
const (
	// GameInitializedNotify opcode = 3945341079 = 0xEB292097
	OpcodeGameInitializedNotifyV2 uint32 = OpcodeGameInitializedNotify

	// GameStartedNotify opcode = 102653531 = 0x061E13DB
	OpcodeGameStartedNotifyV2 uint32 = OpcodeGameStartedNotify

	// GameFinishedNotify opcode = 535291459 = 0x1FE61E43
	OpcodeGameFinishedNotifyV2 uint32 = OpcodeGameFinishedNotify

	// GameCancelledNotify opcode = 388530130 = 0x172AD3D2
	OpcodeGameCancelledNotifyV2 uint32 = OpcodeGameCancelledNotify

	// SecretOpenedNotify opcode = 1202198728 = 0x47A29FC8
	OpcodeSecretOpenedNotifyV2 uint32 = OpcodeSecretOpenedNotify

	// DrawNotify opcode = 317981831 = 0x12F4A487
	OpcodeDrawNotifyV2 uint32 = OpcodeDrawNotify

	// InsufficientBalanceNotify opcode = 4148213171 = 0xF76E49B3
	OpcodeInsufficientBalanceNotifyV2 uint32 = OpcodeInsufficientBalanceNotify

	// Factory Event opcodes (emitted via emit() - appear in out_msgs)
	// From PODGameFactory_PODGameFactory.abi
	OpcodeGameInitializedEvent uint32 = 2904670482
	OpcodeGameStartedEvent     uint32 = 3493528925
	OpcodeGameFinishedEvent    uint32 = 2774366883
	OpcodeGameCancelledEvent   uint32 = 616834666
	OpcodeDrawEvent            uint32 = 2466780489
)

// MessageParserV2 parses TON blockchain messages using tonutils-go Cell parser.
type MessageParserV2 struct{}

var _ InMsgParser = (*MessageParserV2)(nil)

// NewMessageParserV2 creates a new TON message parser.
func NewMessageParserV2() *MessageParserV2 {
	return &MessageParserV2{}
}

// ParseInMsg parses the in_msg JSON from a transaction into a ParsedMessage.
// Returns nil if the message is not a game-related notification.
func (p *MessageParserV2) ParseInMsg(inMsgJSON json.RawMessage) (*ParsedMessage, error) {
	if len(inMsgJSON) == 0 || string(inMsgJSON) == "null" {
		return nil, fmt.Errorf("empty in_msg")
	}

	var inMsg InMsgData
	if err := json.Unmarshal(inMsgJSON, &inMsg); err != nil {
		// Try legacy JSON format (for tests)
		return p.parseLegacyJSON(inMsgJSON)
	}

	// Check if it's a simple JSON format (for tests)
	if inMsg.Message == "" && inMsg.MsgData.Body == "" {
		return p.parseLegacyJSON(inMsgJSON)
	}

	// Try to get message body from 'message' field first
	// If not available, fall back to 'msg_data.body' (base64 BOC)
	var bocData []byte
	var err error

	if inMsg.Message != "" {
		bocData, err = base64.StdEncoding.DecodeString(inMsg.Message)
		if err != nil {
			bocData, err = base64.RawStdEncoding.DecodeString(inMsg.Message)
			if err != nil {
				return nil, fmt.Errorf("failed to decode message: %w", err)
			}
		}
	} else if inMsg.MsgData.Body != "" {
		bocData, err = base64.StdEncoding.DecodeString(inMsg.MsgData.Body)
		if err != nil {
			return nil, fmt.Errorf("failed to decode msg_data.body: %w", err)
		}
	} else {
		return nil, fmt.Errorf("no message body found in in_msg")
	}

	// Parse BOC using tonutils-go
	c, err := cell.FromBOC(bocData)
	if err != nil {
		// Not a valid BOC, might be raw data - try parsing directly
		return p.parseRawData(bocData)
	}

	return p.parseCellMessage(c)
}

// parseRawData tries to parse raw message data (without BOC wrapper)
func (p *MessageParserV2) parseRawData(data []byte) (*ParsedMessage, error) {
	if len(data) < 4 {
		return nil, fmt.Errorf("message too short: %d bytes", len(data))
	}

	// First 4 bytes are opcode (big-endian)
	opcode := uint32(data[0])<<24 | uint32(data[1])<<16 | uint32(data[2])<<8 | uint32(data[3])

	// Check if this is a known game opcode
	if _, ok := GetEventTypeForOpcodeV2(opcode); !ok {
		return nil, fmt.Errorf("unknown opcode: 0x%08X", opcode)
	}

	// Try to create a cell from the remaining data (after opcode)
	builder := cell.BeginCell()
	// Store remaining data as bits
	if len(data) > 4 {
		builder.MustStoreSlice(data[4:], uint(len(data[4:])*8))
	}
	c := builder.EndCell()

	// Create message and parse based on opcode
	msg := &ParsedMessage{
		Opcode: opcode,
	}

	return p.parseMessageDataFromSlice(msg, c.BeginParse(), opcode)
}

// parseCellMessage parses a TON Cell message.
func (p *MessageParserV2) parseCellMessage(c *cell.Cell) (*ParsedMessage, error) {
	slice := c.BeginParse()

	// Read opcode (32 bits)
	opcode, err := slice.LoadUInt(32)
	if err != nil {
		return nil, fmt.Errorf("failed to read opcode: %w", err)
	}

	// Create message
	msg := &ParsedMessage{
		Opcode: uint32(opcode),
	}

	return p.parseMessageDataFromSlice(msg, slice, uint32(opcode))
}

// parseMessageDataFromSlice parses message content from a cell slice based on opcode.
// The opcode has already been read from the slice.
func (p *MessageParserV2) parseMessageDataFromSlice(msg *ParsedMessage, slice *cell.Slice, opcode uint32) (*ParsedMessage, error) {
	switch opcode {
	case OpcodeGameInitializedNotifyV2:
		return p.parseGameInitializedNotifyV2(msg, slice)
	case OpcodeGameInitializedEvent:
		return p.parseGameInitializedEventV2(msg, slice)
	case OpcodeGameStartedNotifyV2:
		return p.parseGameStartedNotifyV2(msg, slice)
	case OpcodeGameStartedEvent:
		return p.parseGameStartedEventV2(msg, slice)
	case OpcodeGameFinishedNotifyV2:
		return p.parseGameFinishedNotifyV2(msg, slice)
	case OpcodeGameFinishedEvent:
		return p.parseGameFinishedEventV2(msg, slice)
	case OpcodeGameCancelledNotifyV2:
		return p.parseGameCancelledNotifyV2(msg, slice)
	case OpcodeGameCancelledEvent:
		return p.parseGameCancelledEventV2(msg, slice)
	case OpcodeSecretOpenedNotifyV2:
		return p.parseSecretOpenedNotifyV2(msg, slice)
	case OpcodeDrawNotifyV2:
		return p.parseDrawNotifyV2(msg, slice)
	case OpcodeDrawEvent:
		return p.parseDrawEventV2(msg, slice)
	case OpcodeInsufficientBalanceNotifyV2:
		return p.parseInsufficientBalanceNotifyV2(msg, slice)
	default:
		return nil, fmt.Errorf("unknown opcode: 0x%08X", opcode)
	}
}

// parseGameInitializedNotifyV2 parses GameInitializedNotify message.
// Structure from ABI:
// - gameId: uint256
// - playerOne: address
// - bidValue: coins
func (p *MessageParserV2) parseGameInitializedNotifyV2(msg *ParsedMessage, slice *cell.Slice) (*ParsedMessage, error) {
	msg.EventType = EventTypeGameInitialized

	// gameId: uint256 (256 bits)
	gameIDBig, err := slice.LoadBigUInt(256)
	if err != nil {
		return nil, fmt.Errorf("GameInitializedNotify: failed to read gameId: %w", err)
	}
	gameID, err := safeUint256ToInt64(gameIDBig, "gameId")
	if err != nil {
		return nil, fmt.Errorf("GameInitializedNotify: %w", err)
	}
	msg.GameID = gameID

	// playerOne: Address (MsgAddress format)
	addr, err := slice.LoadAddr()
	if err != nil {
		return nil, fmt.Errorf("GameInitializedNotify: failed to read playerOne: %w", err)
	}
	msg.PlayerOne = addr.String()

	// bidValue: coins (VarUInteger 16)
	bidValue, err := slice.LoadBigCoins()
	if err != nil {
		return nil, fmt.Errorf("GameInitializedNotify: failed to read bidValue: %w", err)
	}
	msg.BidValue = bidValue

	// Remediated factories append config/protocol fields. Tact stores the tail of
	// the larger message in a reference, while legacy emitted events have exactly
	// 32 bits left here (timestamp) and no refs.
	if slice.BitsLeft() > 32 || slice.RefsNum() > 0 {
		if err := parseGameInitializedConfigSnapshotV2(msg, slice, "GameInitializedNotify"); err != nil {
			return nil, err
		}
	}

	return msg, nil
}

func parseGameInitializedConfigSnapshotV2(msg *ParsedMessage, slice *cell.Slice, label string) error {
	serviceFeeNumerator, err := slice.LoadUInt(32)
	if err != nil {
		return fmt.Errorf("%s: failed to read serviceFeeNumerator: %w", label, err)
	}
	msg.ServiceFeeNumerator = uint32(serviceFeeNumerator)

	referrerFeeNumerator, err := slice.LoadUInt(32)
	if err != nil {
		return fmt.Errorf("%s: failed to read referrerFeeNumerator: %w", label, err)
	}
	msg.ReferrerFeeNumerator = uint32(referrerFeeNumerator)

	waitingForOpenBidSeconds, err := slice.LoadUInt(32)
	if err != nil {
		return fmt.Errorf("%s: failed to read waitingForOpenBidSeconds: %w", label, err)
	}
	msg.WaitingForOpenBidSeconds = uint32(waitingForOpenBidSeconds)

	lowestBid, err := slice.LoadBigCoins()
	if err != nil {
		return fmt.Errorf("%s: failed to read lowestBid: %w", label, err)
	}
	msg.LowestBid = lowestBid

	ref, err := slice.LoadRef()
	if err != nil {
		return fmt.Errorf("%s: failed to read config ref: %w", label, err)
	}

	highestBid, err := ref.LoadBigCoins()
	if err != nil {
		return fmt.Errorf("%s: failed to read highestBid: %w", label, err)
	}
	msg.HighestBid = highestBid

	minReferrerPayoutValue, err := ref.LoadBigCoins()
	if err != nil {
		return fmt.Errorf("%s: failed to read minReferrerPayoutValue: %w", label, err)
	}
	msg.MinReferrerPayoutValue = minReferrerPayoutValue

	feeReceiver, err := ref.LoadAddr()
	if err != nil {
		return fmt.Errorf("%s: failed to read feeReceiver: %w", label, err)
	}
	msg.FeeReceiver = feeReceiver.String()

	protocolVersion, err := ref.LoadUInt(32)
	if err != nil {
		return fmt.Errorf("%s: failed to read protocolVersion: %w", label, err)
	}
	msg.ProtocolVersion = uint32(protocolVersion)

	if msg.Opcode == OpcodeGameInitializedEvent {
		if _, err := ref.LoadUInt(32); err != nil {
			return fmt.Errorf("%s: failed to read timestamp: %w", label, err)
		}
	}

	return nil
}

// parseGameStartedNotifyV2 parses GameStartedNotify message.
// Structure:
// - gameId: uint256
// - playerOne: address
// - playerTwo: address
// - totalGainings: coins
func (p *MessageParserV2) parseGameStartedNotifyV2(msg *ParsedMessage, slice *cell.Slice) (*ParsedMessage, error) {
	msg.EventType = EventTypeGameStarted

	// gameId: uint256
	gameIDBig, err := slice.LoadBigUInt(256)
	if err != nil {
		return nil, fmt.Errorf("GameStartedNotify: failed to read gameId: %w", err)
	}
	gameID, err := safeUint256ToInt64(gameIDBig, "gameId")
	if err != nil {
		return nil, fmt.Errorf("GameStartedNotify: %w", err)
	}
	msg.GameID = gameID

	// playerOne: Address
	addr1, err := slice.LoadAddr()
	if err != nil {
		return nil, fmt.Errorf("GameStartedNotify: failed to read playerOne: %w", err)
	}
	msg.PlayerOne = addr1.String()

	// playerTwo: Address
	addr2, err := slice.LoadAddr()
	if err != nil {
		return nil, fmt.Errorf("GameStartedNotify: failed to read playerTwo: %w", err)
	}
	msg.PlayerTwo = addr2.String()

	// totalGainings: coins
	totalGainings, err := slice.LoadBigCoins()
	if err != nil {
		return nil, fmt.Errorf("GameStartedNotify: failed to read totalGainings: %w", err)
	}
	msg.TotalGainings = totalGainings

	return msg, nil
}

// parseGameFinishedNotifyV2 parses GameFinishedNotify message.
// Structure:
// - gameId: uint256
// - winner: address
// - looser: address
// - totalGainings: coins
func (p *MessageParserV2) parseGameFinishedNotifyV2(msg *ParsedMessage, slice *cell.Slice) (*ParsedMessage, error) {
	msg.EventType = EventTypeGameFinished

	// gameId: uint256
	gameIDBig, err := slice.LoadBigUInt(256)
	if err != nil {
		return nil, fmt.Errorf("GameFinishedNotify: failed to read gameId: %w", err)
	}
	gameID, err := safeUint256ToInt64(gameIDBig, "gameId")
	if err != nil {
		return nil, fmt.Errorf("GameFinishedNotify: %w", err)
	}
	msg.GameID = gameID

	// winner: Address
	winner, err := slice.LoadAddr()
	if err != nil {
		return nil, fmt.Errorf("GameFinishedNotify: failed to read winner: %w", err)
	}
	msg.Winner = winner.String()

	// looser: Address
	looser, err := slice.LoadAddr()
	if err != nil {
		return nil, fmt.Errorf("GameFinishedNotify: failed to read looser: %w", err)
	}
	msg.Looser = looser.String()

	// totalGainings: coins
	totalGainings, err := slice.LoadBigCoins()
	if err != nil {
		return nil, fmt.Errorf("GameFinishedNotify: failed to read totalGainings: %w", err)
	}
	msg.TotalGainings = totalGainings

	return msg, nil
}

// parseGameCancelledNotifyV2 parses GameCancelledNotify message.
// Structure:
// - gameId: uint256
// - playerOne: address
func (p *MessageParserV2) parseGameCancelledNotifyV2(msg *ParsedMessage, slice *cell.Slice) (*ParsedMessage, error) {
	msg.EventType = EventTypeGameCancelled

	// gameId: uint256
	gameIDBig, err := slice.LoadBigUInt(256)
	if err != nil {
		return nil, fmt.Errorf("GameCancelledNotify: failed to read gameId: %w", err)
	}
	gameID, err := safeUint256ToInt64(gameIDBig, "gameId")
	if err != nil {
		return nil, fmt.Errorf("GameCancelledNotify: %w", err)
	}
	msg.GameID = gameID

	// playerOne: Address
	addr, err := slice.LoadAddr()
	if err != nil {
		return nil, fmt.Errorf("GameCancelledNotify: failed to read playerOne: %w", err)
	}
	msg.PlayerOne = addr.String()

	return msg, nil
}

// parseSecretOpenedNotifyV2 parses SecretOpenedNotify message.
// Structure:
// - gameId: uint256
// - player: address
// - coinSide: uint8
func (p *MessageParserV2) parseSecretOpenedNotifyV2(msg *ParsedMessage, slice *cell.Slice) (*ParsedMessage, error) {
	msg.EventType = EventTypeSecretOpened

	// gameId: uint256
	gameIDBig, err := slice.LoadBigUInt(256)
	if err != nil {
		return nil, fmt.Errorf("SecretOpenedNotify: failed to read gameId: %w", err)
	}
	gameID, err := safeUint256ToInt64(gameIDBig, "gameId")
	if err != nil {
		return nil, fmt.Errorf("SecretOpenedNotify: %w", err)
	}
	msg.GameID = gameID

	// player: Address
	addr, err := slice.LoadAddr()
	if err != nil {
		return nil, fmt.Errorf("SecretOpenedNotify: failed to read player: %w", err)
	}
	msg.Player = addr.String()

	// coinSide: uint8
	coinSide, err := slice.LoadUInt(8)
	if err != nil {
		return nil, fmt.Errorf("SecretOpenedNotify: failed to read coinSide: %w", err)
	}
	msg.CoinSide = uint8(coinSide)

	return msg, nil
}

// parseDrawNotifyV2 parses DrawNotify message.
// Structure:
// - gameId: uint256
func (p *MessageParserV2) parseDrawNotifyV2(msg *ParsedMessage, slice *cell.Slice) (*ParsedMessage, error) {
	msg.EventType = EventTypeDraw

	// gameId: uint256
	gameIDBig, err := slice.LoadBigUInt(256)
	if err != nil {
		return nil, fmt.Errorf("DrawNotify: failed to read gameId: %w", err)
	}
	gameID, err := safeUint256ToInt64(gameIDBig, "gameId")
	if err != nil {
		return nil, fmt.Errorf("DrawNotify: %w", err)
	}
	msg.GameID = gameID

	return msg, nil
}

// parseInsufficientBalanceNotifyV2 parses InsufficientBalanceNotify message.
// Structure:
// - gameId: uint256
// - required: coins
// - actual: coins
func (p *MessageParserV2) parseInsufficientBalanceNotifyV2(msg *ParsedMessage, slice *cell.Slice) (*ParsedMessage, error) {
	msg.EventType = EventTypeInsufficientBalance

	// gameId: uint256
	gameIDBig, err := slice.LoadBigUInt(256)
	if err != nil {
		return nil, fmt.Errorf("InsufficientBalanceNotify: failed to read gameId: %w", err)
	}
	gameID, err := safeUint256ToInt64(gameIDBig, "gameId")
	if err != nil {
		return nil, fmt.Errorf("InsufficientBalanceNotify: %w", err)
	}
	msg.GameID = gameID

	// required: coins
	required, err := slice.LoadBigCoins()
	if err != nil {
		return nil, fmt.Errorf("InsufficientBalanceNotify: failed to read required: %w", err)
	}
	msg.Required = required

	// actual: coins
	actual, err := slice.LoadBigCoins()
	if err != nil {
		return nil, fmt.Errorf("InsufficientBalanceNotify: failed to read actual: %w", err)
	}
	msg.Actual = actual

	return msg, nil
}

// parseGameInitializedEventV2 parses the factory-emitted GameInitializedEvent message.
// Runtime persistence intentionally maps emitted event opcodes onto the same canonical
// event types as the notify messages so the downstream persistence handlers remain unchanged.
func (p *MessageParserV2) parseGameInitializedEventV2(msg *ParsedMessage, slice *cell.Slice) (*ParsedMessage, error) {
	parsedMsg, err := p.parseGameInitializedNotifyV2(msg, slice)
	if err != nil {
		return nil, err
	}

	if slice.BitsLeft() >= 32 {
		if err := loadEmittedEventTimestamp(slice, "GameInitializedEvent"); err != nil {
			return nil, err
		}
	}

	return parsedMsg, nil
}

// parseGameStartedEventV2 parses the factory-emitted GameStartedEvent message.
func (p *MessageParserV2) parseGameStartedEventV2(msg *ParsedMessage, slice *cell.Slice) (*ParsedMessage, error) {
	parsedMsg, err := p.parseGameStartedNotifyV2(msg, slice)
	if err != nil {
		return nil, err
	}

	if err := loadEmittedEventTimestamp(slice, "GameStartedEvent"); err != nil {
		return nil, err
	}

	return parsedMsg, nil
}

// parseGameFinishedEventV2 parses the factory-emitted GameFinishedEvent message.
func (p *MessageParserV2) parseGameFinishedEventV2(msg *ParsedMessage, slice *cell.Slice) (*ParsedMessage, error) {
	parsedMsg, err := p.parseGameFinishedNotifyV2(msg, slice)
	if err != nil {
		return nil, err
	}

	if err := loadEmittedEventTimestamp(slice, "GameFinishedEvent"); err != nil {
		return nil, err
	}

	return parsedMsg, nil
}

// parseGameCancelledEventV2 parses the factory-emitted GameCancelledEvent message.
func (p *MessageParserV2) parseGameCancelledEventV2(msg *ParsedMessage, slice *cell.Slice) (*ParsedMessage, error) {
	parsedMsg, err := p.parseGameCancelledNotifyV2(msg, slice)
	if err != nil {
		return nil, err
	}

	if err := loadEmittedEventTimestamp(slice, "GameCancelledEvent"); err != nil {
		return nil, err
	}

	return parsedMsg, nil
}

// parseDrawEventV2 parses the factory-emitted DrawEvent message.
func (p *MessageParserV2) parseDrawEventV2(msg *ParsedMessage, slice *cell.Slice) (*ParsedMessage, error) {
	parsedMsg, err := p.parseDrawNotifyV2(msg, slice)
	if err != nil {
		return nil, err
	}

	if err := loadEmittedEventTimestamp(slice, "DrawEvent"); err != nil {
		return nil, err
	}

	return parsedMsg, nil
}

func loadEmittedEventTimestamp(slice *cell.Slice, eventName string) error {
	if _, err := slice.LoadUInt(32); err != nil {
		return fmt.Errorf("%s: failed to read timestamp: %w", eventName, err)
	}

	return nil
}

// parseLegacyJSON handles the legacy JSON format used in tests.
func (p *MessageParserV2) parseLegacyJSON(inMsgJSON json.RawMessage) (*ParsedMessage, error) {
	return parseLegacyParsedMessage(inMsgJSON)
}

// GetEventTypeForOpcodeV2 returns the event type string for a given opcode.
func GetEventTypeForOpcodeV2(opcode uint32) (string, bool) {
	return GetEventTypeForOpcode(opcode)
}

// Backward compatibility - keep old variable names pointing to correct values
func init() {
	// Verify that we're using the same address package
	_ = address.NewAddress(0, 0, make([]byte, 32))
}
