package toncenter

import (
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"math/big"

	"github.com/xssnick/tonutils-go/address"
)

// Message opcodes for game contract notifications.
// These are auto-generated by Tact compiler - values from PODGame_Game.abi.
// Header values from ABI: "GameInitializedNotify": {"header": 3945341079}
const (
	// GameInitializedNotify opcode = 3945341079 = 0xEB292097
	OpcodeGameInitializedNotify uint32 = 3945341079

	// GameStartedNotify opcode = 102653531 = 0x061E13DB
	OpcodeGameStartedNotify uint32 = 102653531

	// GameFinishedNotify opcode = 535291459 = 0x1FE61E43
	OpcodeGameFinishedNotify uint32 = 535291459

	// GameCancelledNotify opcode = 388530130 = 0x172AD3D2
	OpcodeGameCancelledNotify uint32 = 388530130

	// SecretOpenedNotify opcode = 1202198728 = 0x47A29FC8
	OpcodeSecretOpenedNotify uint32 = 1202198728

	// DrawNotify opcode = 317981831 = 0x12F4A487
	OpcodeDrawNotify uint32 = 317981831

	// InsufficientBalanceNotify opcode = 4148213171 = 0xF76E49B3
	OpcodeInsufficientBalanceNotify uint32 = 4148213171
)

// EventType constants matching entity.GameEvent types.
// These must match the constants in entity/game_event.go
const (
	EventTypeGameInitialized     = "GameInitializedNotify"
	EventTypeGameStarted         = "GameStartedNotify"
	EventTypeGameFinished        = "GameFinishedNotify"
	EventTypeGameCancelled       = "GameCancelledNotify"
	EventTypeSecretOpened        = "SecretOpenedNotify"
	EventTypeDraw                = "DrawNotify"
	EventTypeInsufficientBalance = "InsufficientBalanceNotify"
)

// ParsedMessage represents a parsed TON message from blockchain.
type ParsedMessage struct {
	Opcode        uint32
	EventType     string
	GameID        int64
	PlayerOne     string
	PlayerTwo     string
	BidValue      *big.Int
	TotalGainings *big.Int
	Winner        string
	Looser        string
	Player        string
	CoinSide      uint8
	Required      *big.Int
	Actual        *big.Int
	RawData       []byte
}

// InMsgData represents the in_msg structure from TON Center API.
type InMsgData struct {
	Type        string `json:"@type"`
	Source      string `json:"source"`
	Destination string `json:"destination"`
	Value       string `json:"value"`
	BodyHash    string `json:"body_hash"`
	MsgData     struct {
		Type string `json:"@type"`
		Body string `json:"body"`
	} `json:"msg_data"`
	Message string `json:"message"`
}

// MessageParser parses TON blockchain messages into structured events.
type MessageParser struct{}

// NewMessageParser creates a new TON message parser.
func NewMessageParser() *MessageParser {
	return &MessageParser{}
}

// ParseInMsg parses the in_msg JSON from a transaction into a ParsedMessage.
// Returns nil if the message is not a game-related notification.
// Supports two formats:
// 1. BOC-encoded messages from real TON blockchain (production)
// 2. JSON messages with event_type and game_id fields (testing/legacy)
func (p *MessageParser) ParseInMsg(inMsgJSON json.RawMessage) (*ParsedMessage, error) {
	if len(inMsgJSON) == 0 || string(inMsgJSON) == "null" {
		return nil, fmt.Errorf("empty in_msg")
	}

	var inMsg InMsgData
	if err := json.Unmarshal(inMsgJSON, &inMsg); err != nil {
		// Try legacy JSON format (for tests)
		return p.parseLegacyJSON(inMsgJSON)
	}

	// Check if it's a simple JSON format (for tests)
	// Real TON messages have "message" or "msg_data.body" fields
	if inMsg.Message == "" && inMsg.MsgData.Body == "" {
		return p.parseLegacyJSON(inMsgJSON)
	}

	// Try to get message body from 'message' field first (already decoded)
	// If not available, fall back to 'msg_data.body' (base64 BOC)
	var messageData []byte
	var err error

	if inMsg.Message != "" {
		messageData, err = base64.StdEncoding.DecodeString(inMsg.Message)
		if err != nil {
			// Try URL-safe base64
			messageData, err = base64.RawStdEncoding.DecodeString(inMsg.Message)
			if err != nil {
				return nil, fmt.Errorf("failed to decode message: %w", err)
			}
		}
	} else if inMsg.MsgData.Body != "" {
		// Parse BOC from msg_data.body
		messageData, err = base64.StdEncoding.DecodeString(inMsg.MsgData.Body)
		if err != nil {
			return nil, fmt.Errorf("failed to decode msg_data.body: %w", err)
		}
	} else {
		return nil, fmt.Errorf("no message body found in in_msg")
	}

	if len(messageData) < 4 {
		return nil, fmt.Errorf("message too short: %d bytes", len(messageData))
	}

	// First 4 bytes are the opcode (big-endian)
	opcode := binary.BigEndian.Uint32(messageData[:4])

	return p.parseMessageByOpcode(opcode, messageData[4:], messageData)
}

// parseLegacyJSON handles the legacy JSON format used in tests.
// Expected format: {"event_type": "...", "game_id": 123, ...}
func (p *MessageParser) parseLegacyJSON(inMsgJSON json.RawMessage) (*ParsedMessage, error) {
	var data map[string]interface{}
	if err := json.Unmarshal(inMsgJSON, &data); err != nil {
		return nil, fmt.Errorf("failed to parse legacy JSON: %w", err)
	}

	eventType, ok := data["event_type"].(string)
	if !ok {
		return nil, fmt.Errorf("missing or invalid event_type in legacy JSON")
	}

	gameIDFloat, ok := data["game_id"].(float64)
	if !ok {
		return nil, fmt.Errorf("missing or invalid game_id in legacy JSON")
	}

	msg := &ParsedMessage{
		EventType: eventType,
		GameID:    int64(gameIDFloat),
	}

	// Extract optional fields
	if playerOne, ok := data["player_one"].(string); ok {
		msg.PlayerOne = playerOne
	}
	if playerTwo, ok := data["player_two"].(string); ok {
		msg.PlayerTwo = playerTwo
	}
	if winner, ok := data["winner"].(string); ok {
		msg.Winner = winner
	}
	if looser, ok := data["looser"].(string); ok {
		msg.Looser = looser
	}
	if player, ok := data["player"].(string); ok {
		msg.Player = player
	}
	if betAmount, ok := data["bet_amount"].(string); ok {
		msg.BidValue, _ = new(big.Int).SetString(betAmount, 10)
	}
	if coinSide, ok := data["coin_side"].(float64); ok {
		msg.CoinSide = uint8(coinSide)
	}

	return msg, nil
}

// parseMessageByOpcode parses message data based on the opcode.
func (p *MessageParser) parseMessageByOpcode(opcode uint32, data []byte, rawData []byte) (*ParsedMessage, error) {
	msg := &ParsedMessage{
		Opcode:  opcode,
		RawData: rawData,
	}

	switch opcode {
	case OpcodeGameInitializedNotify:
		return p.parseGameInitializedNotify(msg, data)
	case OpcodeGameStartedNotify:
		return p.parseGameStartedNotify(msg, data)
	case OpcodeGameFinishedNotify:
		return p.parseGameFinishedNotify(msg, data)
	case OpcodeGameCancelledNotify:
		return p.parseGameCancelledNotify(msg, data)
	case OpcodeSecretOpenedNotify:
		return p.parseSecretOpenedNotify(msg, data)
	case OpcodeDrawNotify:
		return p.parseDrawNotify(msg, data)
	case OpcodeInsufficientBalanceNotify:
		return p.parseInsufficientBalanceNotify(msg, data)
	default:
		return nil, fmt.Errorf("unknown opcode: 0x%08X", opcode)
	}
}

// parseGameInitializedNotify parses GameInitializedNotify message.
// Structure: gameId: uint256, playerOne: Address, bidValue: coins
func (p *MessageParser) parseGameInitializedNotify(msg *ParsedMessage, data []byte) (*ParsedMessage, error) {
	msg.EventType = EventTypeGameInitialized

	offset := 0

	// gameId: uint256 (32 bytes)
	if len(data) < offset+32 {
		return nil, fmt.Errorf("GameInitializedNotify: not enough data for gameId")
	}
	gameID := new(big.Int).SetBytes(data[offset : offset+32])
	msg.GameID = gameID.Int64()
	offset += 32

	// playerOne: Address (267 bits = ~34 bytes in cell format)
	// TON addresses are stored as: workchain (1 byte) + hash (32 bytes)
	if len(data) < offset+33 {
		return nil, fmt.Errorf("GameInitializedNotify: not enough data for playerOne")
	}
	addr, err := p.parseAddress(data[offset : offset+33])
	if err != nil {
		return nil, fmt.Errorf("GameInitializedNotify: failed to parse playerOne: %w", err)
	}
	msg.PlayerOne = addr
	offset += 33

	// bidValue: coins (VarUInt16 format, up to 16 bytes)
	if len(data) > offset {
		bidValue, bytesRead := p.parseCoins(data[offset:])
		msg.BidValue = bidValue
		offset += bytesRead
	}

	return msg, nil
}

// parseGameStartedNotify parses GameStartedNotify message.
// Structure: gameId: uint256, playerOne: Address, playerTwo: Address, totalGainings: coins
func (p *MessageParser) parseGameStartedNotify(msg *ParsedMessage, data []byte) (*ParsedMessage, error) {
	msg.EventType = EventTypeGameStarted

	offset := 0

	// gameId: uint256 (32 bytes)
	if len(data) < offset+32 {
		return nil, fmt.Errorf("GameStartedNotify: not enough data for gameId")
	}
	gameID := new(big.Int).SetBytes(data[offset : offset+32])
	msg.GameID = gameID.Int64()
	offset += 32

	// playerOne: Address
	if len(data) < offset+33 {
		return nil, fmt.Errorf("GameStartedNotify: not enough data for playerOne")
	}
	addr1, err := p.parseAddress(data[offset : offset+33])
	if err != nil {
		return nil, fmt.Errorf("GameStartedNotify: failed to parse playerOne: %w", err)
	}
	msg.PlayerOne = addr1
	offset += 33

	// playerTwo: Address
	if len(data) < offset+33 {
		return nil, fmt.Errorf("GameStartedNotify: not enough data for playerTwo")
	}
	addr2, err := p.parseAddress(data[offset : offset+33])
	if err != nil {
		return nil, fmt.Errorf("GameStartedNotify: failed to parse playerTwo: %w", err)
	}
	msg.PlayerTwo = addr2
	offset += 33

	// totalGainings: coins
	if len(data) > offset {
		totalGainings, _ := p.parseCoins(data[offset:])
		msg.TotalGainings = totalGainings
	}

	return msg, nil
}

// parseGameFinishedNotify parses GameFinishedNotify message.
// Structure: gameId: uint256, winner: Address, looser: Address, totalGainings: coins
func (p *MessageParser) parseGameFinishedNotify(msg *ParsedMessage, data []byte) (*ParsedMessage, error) {
	msg.EventType = EventTypeGameFinished

	offset := 0

	// gameId: uint256
	if len(data) < offset+32 {
		return nil, fmt.Errorf("GameFinishedNotify: not enough data for gameId")
	}
	gameID := new(big.Int).SetBytes(data[offset : offset+32])
	msg.GameID = gameID.Int64()
	offset += 32

	// winner: Address
	if len(data) < offset+33 {
		return nil, fmt.Errorf("GameFinishedNotify: not enough data for winner")
	}
	winner, err := p.parseAddress(data[offset : offset+33])
	if err != nil {
		return nil, fmt.Errorf("GameFinishedNotify: failed to parse winner: %w", err)
	}
	msg.Winner = winner
	offset += 33

	// looser: Address
	if len(data) < offset+33 {
		return nil, fmt.Errorf("GameFinishedNotify: not enough data for looser")
	}
	looser, err := p.parseAddress(data[offset : offset+33])
	if err != nil {
		return nil, fmt.Errorf("GameFinishedNotify: failed to parse looser: %w", err)
	}
	msg.Looser = looser
	offset += 33

	// totalGainings: coins
	if len(data) > offset {
		totalGainings, _ := p.parseCoins(data[offset:])
		msg.TotalGainings = totalGainings
	}

	return msg, nil
}

// parseGameCancelledNotify parses GameCancelledNotify message.
// Structure: gameId: uint256, playerOne: Address
func (p *MessageParser) parseGameCancelledNotify(msg *ParsedMessage, data []byte) (*ParsedMessage, error) {
	msg.EventType = EventTypeGameCancelled

	offset := 0

	// gameId: uint256
	if len(data) < offset+32 {
		return nil, fmt.Errorf("GameCancelledNotify: not enough data for gameId")
	}
	gameID := new(big.Int).SetBytes(data[offset : offset+32])
	msg.GameID = gameID.Int64()
	offset += 32

	// playerOne: Address
	if len(data) < offset+33 {
		return nil, fmt.Errorf("GameCancelledNotify: not enough data for playerOne")
	}
	addr, err := p.parseAddress(data[offset : offset+33])
	if err != nil {
		return nil, fmt.Errorf("GameCancelledNotify: failed to parse playerOne: %w", err)
	}
	msg.PlayerOne = addr

	return msg, nil
}

// parseSecretOpenedNotify parses SecretOpenedNotify message.
// Structure: gameId: uint256, player: Address, coinSide: uint8
func (p *MessageParser) parseSecretOpenedNotify(msg *ParsedMessage, data []byte) (*ParsedMessage, error) {
	msg.EventType = EventTypeSecretOpened

	offset := 0

	// gameId: uint256
	if len(data) < offset+32 {
		return nil, fmt.Errorf("SecretOpenedNotify: not enough data for gameId")
	}
	gameID := new(big.Int).SetBytes(data[offset : offset+32])
	msg.GameID = gameID.Int64()
	offset += 32

	// player: Address
	if len(data) < offset+33 {
		return nil, fmt.Errorf("SecretOpenedNotify: not enough data for player")
	}
	addr, err := p.parseAddress(data[offset : offset+33])
	if err != nil {
		return nil, fmt.Errorf("SecretOpenedNotify: failed to parse player: %w", err)
	}
	msg.Player = addr
	offset += 33

	// coinSide: uint8
	if len(data) > offset {
		msg.CoinSide = data[offset]
	}

	return msg, nil
}

// parseDrawNotify parses DrawNotify message.
// Structure: gameId: uint256
func (p *MessageParser) parseDrawNotify(msg *ParsedMessage, data []byte) (*ParsedMessage, error) {
	msg.EventType = EventTypeDraw

	// gameId: uint256
	if len(data) < 32 {
		return nil, fmt.Errorf("DrawNotify: not enough data for gameId")
	}
	gameID := new(big.Int).SetBytes(data[:32])
	msg.GameID = gameID.Int64()

	return msg, nil
}

// parseInsufficientBalanceNotify parses InsufficientBalanceNotify message.
// Structure: gameId: uint256, required: coins, actual: coins
func (p *MessageParser) parseInsufficientBalanceNotify(msg *ParsedMessage, data []byte) (*ParsedMessage, error) {
	msg.EventType = EventTypeInsufficientBalance

	offset := 0

	// gameId: uint256
	if len(data) < offset+32 {
		return nil, fmt.Errorf("InsufficientBalanceNotify: not enough data for gameId")
	}
	gameID := new(big.Int).SetBytes(data[offset : offset+32])
	msg.GameID = gameID.Int64()
	offset += 32

	// required: coins
	if len(data) > offset {
		required, bytesRead := p.parseCoins(data[offset:])
		msg.Required = required
		offset += bytesRead
	}

	// actual: coins
	if len(data) > offset {
		actual, _ := p.parseCoins(data[offset:])
		msg.Actual = actual
	}

	return msg, nil
}

// parseAddress parses a TON address from raw bytes.
// Format: workchain (1 byte) + hash (32 bytes)
func (p *MessageParser) parseAddress(data []byte) (string, error) {
	if len(data) < 33 {
		return "", fmt.Errorf("address data too short: %d bytes", len(data))
	}

	workchain := int8(data[0])
	hash := data[1:33]

	// Use tonutils-go address library to format
	addr := address.NewAddress(0, byte(workchain), hash)
	return addr.String(), nil
}

// parseCoins parses a coins value (VarUInt16 format).
// Returns the value and number of bytes consumed.
func (p *MessageParser) parseCoins(data []byte) (*big.Int, int) {
	if len(data) == 0 {
		return big.NewInt(0), 0
	}

	// First byte indicates the number of bytes used for the value
	length := int(data[0])
	if length == 0 {
		return big.NewInt(0), 1
	}

	if len(data) < 1+length {
		return big.NewInt(0), 1
	}

	value := new(big.Int).SetBytes(data[1 : 1+length])
	return value, 1 + length
}

// GetEventTypeForOpcode returns the event type string for a given opcode.
func GetEventTypeForOpcode(opcode uint32) (string, bool) {
	switch opcode {
	case OpcodeGameInitializedNotify:
		return EventTypeGameInitialized, true
	case OpcodeGameStartedNotify:
		return EventTypeGameStarted, true
	case OpcodeGameFinishedNotify:
		return EventTypeGameFinished, true
	case OpcodeGameCancelledNotify:
		return EventTypeGameCancelled, true
	case OpcodeSecretOpenedNotify:
		return EventTypeSecretOpened, true
	case OpcodeDrawNotify:
		return EventTypeDraw, true
	case OpcodeInsufficientBalanceNotify:
		return EventTypeInsufficientBalance, true
	default:
		return "", false
	}
}
