// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "POD Game Team"
        },
        "license": {
            "name": "BUSL-1.1"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/cancel-reservations": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cancel-reservations"
                ],
                "summary": "List active cancel reservations for a wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet address",
                        "name": "wallet",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.CancelReservationListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/games": {
            "get": {
                "description": "Retrieve list of games filtered by status with pagination support. Game payloads may include remediated factory config/protocol fields projected from on-chain events; reservation data is advisory and on-chain status remains authoritative.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Get available games",
                "parameters": [
                    {
                        "enum": [
                            0,
                            1,
                            2,
                            3,
                            4
                        ],
                        "type": "integer",
                        "default": 1,
                        "description": "Filter by game status (0-4)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Maximum number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Number of results to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of games",
                        "schema": {
                            "$ref": "#/definitions/rest.GameListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/games/activity/search": {
            "get": {
                "description": "Searches queue-oriented activity items by wallet, opponent, or game identifier.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Search activity surfaces",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Optional wallet address",
                        "name": "wallet",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Optional queue scope",
                        "name": "queue",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Maximum number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Number of results to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.GameActivitySearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/games/activity/{queueKey}": {
            "get": {
                "description": "Returns queue-oriented activity items for joinable, my-active, reveal-required, expired-attention, or history views.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Get a player-facing activity queue",
                "parameters": [
                    {
                        "enum": [
                            "joinable",
                            "my-active",
                            "reveal-required",
                            "expired-attention",
                            "history"
                        ],
                        "type": "string",
                        "description": "Queue key",
                        "name": "queueKey",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Optional wallet address used for player-relative queue classification",
                        "name": "wallet",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Maximum number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Number of results to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.GameActivityQueueResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/games/{gameId}": {
            "get": {
                "description": "Retrieve detailed information for a specific game by ID, including projected remediated factory config/protocol fields when available. Backend read models are indexed views of on-chain state.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Get game details",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Game details",
                        "schema": {
                            "$ref": "#/definitions/entity.Game"
                        }
                    },
                    "400": {
                        "description": "Invalid game ID",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Game not found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/games/{gameId}/cancel-reservation": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cancel-reservations"
                ],
                "summary": "Get current cancel reservation for a game",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.CancelReservationEnvelope"
                        }
                    },
                    "204": {
                        "description": "No cancel reservation exists"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/games/{gameId}/cancel-reserve": {
            "post": {
                "description": "Advisory creator-only lock that blocks conflicting join attempts while the creator confirms a cancel transaction.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cancel-reservations"
                ],
                "summary": "Reserve cancel coordination for a waiting game",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cancel reservation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.CancelReserveRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.CancelReservationEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "cancel-reservations"
                ],
                "summary": "Cancel a cancel reservation (holder-only)",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cancellation request with wallet address",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.CancelReserveRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Cancelled"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/games/{gameId}/expired-claim": {
            "get": {
                "description": "Returns the current additive expired-follow-up claim for the specified game.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Get expired-follow-up claim",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ExpiredClaimEnvelope"
                        }
                    },
                    "204": {
                        "description": "No expired-follow-up claim exists"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates or resumes an additive expired-follow-up claim for an ended game that still requires attention.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Create expired-follow-up claim",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Expired claim request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.ExpiredClaimRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.ExpiredClaimEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Releases the current expired-follow-up claim held by the requesting wallet.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Release expired-follow-up claim",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Expired claim release request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.ExpiredClaimRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Claim released"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/games/{gameId}/reservation": {
            "get": {
                "description": "Get the current reservation status for a specific game",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservations"
                ],
                "summary": "Get game reservation",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reservation details",
                        "schema": {
                            "$ref": "#/definitions/rest.ReserveGameResponse"
                        }
                    },
                    "204": {
                        "description": "No reservation exists for this game"
                    },
                    "400": {
                        "description": "Invalid game ID",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/games/{gameId}/reserve": {
            "post": {
                "description": "Reserve a game for a specific wallet address to prevent other players from joining",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservations"
                ],
                "summary": "Reserve a game",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reservation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.ReserveRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Reservation created",
                        "schema": {
                            "$ref": "#/definitions/rest.ReserveGameResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Game not found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Game already reserved or conflict",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Cancel an existing reservation for a game. Only the reservation holder can cancel.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservations"
                ],
                "summary": "Cancel a game reservation",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cancellation request with wallet address",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.ReserveRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Reservation cancelled"
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not the reservation holder",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Reservation not found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/games/{gameId}/reveal-reservation": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reveal-reservations"
                ],
                "summary": "Get current reveal reservation for a game",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.RevealReservationEnvelope"
                        }
                    },
                    "204": {
                        "description": "No reveal reservation exists"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/games/{gameId}/reveal-reserve": {
            "post": {
                "description": "Off-chain advisory lock that prevents two concurrent callers from sending the same OpenBid for the same game.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reveal-reservations"
                ],
                "summary": "Reserve the reveal slot for a game",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reveal reservation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.RevealReserveRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.RevealReservationEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "reveal-reservations"
                ],
                "summary": "Cancel a reveal reservation (holder-only)",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cancellation request with wallet address",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.RevealReserveRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Cancelled"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/health": {
            "get": {
                "description": "Returns service health status including database connectivity, TON Center reachability, active event source, and parser checkpoint/recovery details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "$ref": "#/definitions/rest.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service is unhealthy",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/reservations": {
            "get": {
                "description": "Get all active reservations for a specific wallet address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservations"
                ],
                "summary": "List reservations by wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet address",
                        "name": "wallet",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of reservations",
                        "schema": {
                            "$ref": "#/definitions/rest.ListReservationsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid wallet address",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/reveal-reservations": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reveal-reservations"
                ],
                "summary": "List active reveal reservations for a wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet address",
                        "name": "wallet",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.RevealReservationListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/reveal-reserve": {
            "post": {
                "description": "All-or-nothing reservation. Useful for piggyback OpenBid that bundles several game IDs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reveal-reservations"
                ],
                "summary": "Reserve the reveal slot for a batch of games (atomic)",
                "parameters": [
                    {
                        "description": "Batched reveal reservation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.RevealReserveBatchRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.RevealReservationListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{address}": {
            "get": {
                "description": "Retrieve user profile information including statistics (total games, wins, losses)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user profile",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\"",
                        "description": "TON wallet address (EQ...)",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User profile with statistics",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "400": {
                        "description": "Invalid wallet address format",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{address}/activity-summary": {
            "get": {
                "description": "Returns the additive queue counts used by the activity shell for the specified wallet.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get queue summary for a wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "TON wallet address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.PlayerActivitySummary"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{address}/history": {
            "get": {
                "description": "Retrieve paginated list of games where the user participated (as player 1 or player 2)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user game history",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\"",
                        "description": "TON wallet address (EQ...)",
                        "name": "address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of games to return (default: 20, max: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated game history",
                        "schema": {
                            "$ref": "#/definitions/rest.GameHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{address}/referrals": {
            "get": {
                "description": "Retrieve aggregated referral statistics including total referrals, total earnings, and games referred",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get referral statistics",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\"",
                        "description": "TON wallet address (EQ...)",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Referral statistics",
                        "schema": {
                            "$ref": "#/definitions/entity.ReferralStats"
                        }
                    },
                    "400": {
                        "description": "Invalid wallet address format",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.ActionClaim": {
            "type": "object",
            "properties": {
                "claim_type": {
                    "$ref": "#/definitions/entity.ActionClaimType"
                },
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "game_id": {
                    "type": "integer"
                },
                "holder_wallet": {
                    "type": "string"
                },
                "release_reason": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/entity.ActionClaimStatus"
                }
            }
        },
        "entity.ActionClaimStatus": {
            "type": "string",
            "enum": [
                "active",
                "released",
                "expired"
            ],
            "x-enum-varnames": [
                "ActionClaimStatusActive",
                "ActionClaimStatusReleased",
                "ActionClaimStatusExpired"
            ]
        },
        "entity.ActionClaimType": {
            "type": "string",
            "enum": [
                "join",
                "cancel",
                "reveal",
                "expired_follow_up"
            ],
            "x-enum-varnames": [
                "ActionClaimTypeJoin",
                "ActionClaimTypeCancel",
                "ActionClaimTypeReveal",
                "ActionClaimTypeExpiredFollowUp"
            ]
        },
        "entity.ActivityQueueKey": {
            "type": "string",
            "enum": [
                "joinable",
                "my-active",
                "reveal-required",
                "expired-attention",
                "history"
            ],
            "x-enum-varnames": [
                "ActivityQueueJoinable",
                "ActivityQueueMyActive",
                "ActivityQueueRevealRequired",
                "ActivityQueueExpiredAttention",
                "ActivityQueueHistory"
            ]
        },
        "entity.Game": {
            "type": "object",
            "properties": {
                "bet_amount": {
                    "description": "nanotons",
                    "type": "integer"
                },
                "complete_tx_hash": {
                    "type": "string"
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "fee_receiver_address": {
                    "type": "string"
                },
                "game_id": {
                    "type": "integer"
                },
                "highest_bid_allowed": {
                    "type": "integer"
                },
                "init_tx_hash": {
                    "type": "string"
                },
                "join_tx_hash": {
                    "type": "string"
                },
                "joined_at": {
                    "type": "string"
                },
                "lowest_bid_allowed": {
                    "type": "integer"
                },
                "min_referrer_payout_value": {
                    "type": "integer"
                },
                "payout_amount": {
                    "type": "integer"
                },
                "player_one_address": {
                    "type": "string"
                },
                "player_one_choice": {
                    "description": "1=CLOSED, 2=HEADS, 3=TAILS",
                    "type": "integer"
                },
                "player_one_referrer": {
                    "type": "string"
                },
                "player_two_address": {
                    "type": "string"
                },
                "player_two_choice": {
                    "type": "integer"
                },
                "player_two_referrer": {
                    "type": "string"
                },
                "protocol_version": {
                    "type": "integer"
                },
                "referrer_fee_numerator": {
                    "type": "integer"
                },
                "reveal_tx_hash": {
                    "type": "string"
                },
                "revealed_at": {
                    "type": "string"
                },
                "service_fee_numerator": {
                    "type": "integer"
                },
                "status": {
                    "description": "0-4 (see constants above)",
                    "type": "integer"
                },
                "waiting_timeout_seconds": {
                    "type": "integer"
                },
                "winner_address": {
                    "type": "string"
                }
            }
        },
        "entity.PlayerActivityGame": {
            "type": "object",
            "properties": {
                "active_claims": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.ActionClaim"
                    }
                },
                "game": {
                    "$ref": "#/definitions/entity.Game"
                },
                "is_owned_by_player": {
                    "type": "boolean"
                },
                "latest_activity_at": {
                    "type": "string"
                },
                "next_action": {
                    "$ref": "#/definitions/entity.PlayerActivityNextAction"
                },
                "queue_key": {
                    "$ref": "#/definitions/entity.ActivityQueueKey"
                },
                "requires_attention": {
                    "type": "boolean"
                }
            }
        },
        "entity.PlayerActivityNextAction": {
            "type": "string",
            "enum": [
                "join",
                "resume_join",
                "wait_for_join_window",
                "resume_cancel",
                "wait_for_cancel_resolution",
                "wait_for_opponent",
                "reveal",
                "resume_reveal",
                "wait_for_reveal",
                "review_result",
                "resume_review_result",
                "wait_for_review_window",
                "browse_history"
            ],
            "x-enum-varnames": [
                "ActivityNextActionJoin",
                "ActivityNextActionResumeJoin",
                "ActivityNextActionWaitForJoinWindow",
                "ActivityNextActionResumeCancel",
                "ActivityNextActionWaitForCancel",
                "ActivityNextActionWaitForOpponent",
                "ActivityNextActionReveal",
                "ActivityNextActionResumeReveal",
                "ActivityNextActionWaitForReveal",
                "ActivityNextActionReviewResult",
                "ActivityNextActionResumeReview",
                "ActivityNextActionWaitForReview",
                "ActivityNextActionBrowseHistory"
            ]
        },
        "entity.PlayerActivitySummary": {
            "type": "object",
            "properties": {
                "expired_attention_count": {
                    "type": "integer"
                },
                "history_count": {
                    "type": "integer"
                },
                "joinable_count": {
                    "type": "integer"
                },
                "last_activity_at": {
                    "type": "string"
                },
                "my_active_count": {
                    "type": "integer"
                },
                "reveal_required_count": {
                    "type": "integer"
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "entity.ReferralStats": {
            "type": "object",
            "properties": {
                "games_referred": {
                    "description": "Total games where this wallet was referrer",
                    "type": "integer"
                },
                "total_referral_earnings": {
                    "description": "Total earnings in nanotons",
                    "type": "integer"
                },
                "total_referrals": {
                    "description": "Total unique referrals made by this wallet",
                    "type": "integer"
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "entity.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "telegram_user_id": {
                    "description": "Nullable for blockchain-only users",
                    "type": "integer"
                },
                "telegram_username": {
                    "type": "string"
                },
                "total_games_played": {
                    "type": "integer"
                },
                "total_losses": {
                    "type": "integer"
                },
                "total_referral_earnings": {
                    "description": "nanotons",
                    "type": "integer"
                },
                "total_referrals": {
                    "type": "integer"
                },
                "total_wins": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "rest.CancelReservationEnvelope": {
            "type": "object",
            "properties": {
                "reservation": {
                    "$ref": "#/definitions/rest.CancelReservationResponse"
                }
            }
        },
        "rest.CancelReservationListResponse": {
            "type": "object",
            "properties": {
                "reservations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.CancelReservationResponse"
                    }
                }
            }
        },
        "rest.CancelReservationResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "game_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "rest.CancelReserveRequest": {
            "type": "object",
            "required": [
                "wallet_address"
            ],
            "properties": {
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "rest.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "rest.ExpiredClaimEnvelope": {
            "type": "object",
            "properties": {
                "claim": {
                    "$ref": "#/definitions/rest.ExpiredClaimResponse"
                }
            }
        },
        "rest.ExpiredClaimRequest": {
            "type": "object",
            "required": [
                "wallet_address"
            ],
            "properties": {
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "rest.ExpiredClaimResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "game_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "rest.GameActivityQueueResponse": {
            "type": "object",
            "properties": {
                "attention_required": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.PlayerActivityGame"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "queue_key": {
                    "$ref": "#/definitions/entity.ActivityQueueKey"
                },
                "summary": {
                    "$ref": "#/definitions/entity.PlayerActivitySummary"
                },
                "title": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "rest.GameActivitySearchResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.PlayerActivityGame"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "offset": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                },
                "queue_scope": {
                    "type": "string"
                },
                "summary": {
                    "$ref": "#/definitions/entity.PlayerActivitySummary"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "rest.GameHistoryResponse": {
            "type": "object",
            "properties": {
                "games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Game"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "rest.GameListResponse": {
            "type": "object",
            "properties": {
                "games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.GameWithReservation"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "rest.GameWithReservation": {
            "type": "object",
            "properties": {
                "game": {
                    "$ref": "#/definitions/entity.Game"
                },
                "reservation": {
                    "$ref": "#/definitions/rest.Reservation"
                }
            }
        },
        "rest.HealthResponse": {
            "type": "object",
            "properties": {
                "database": {
                    "description": "PostgreSQL connectivity state.",
                    "type": "string",
                    "enum": [
                        "connected",
                        "disconnected",
                        "not_configured"
                    ]
                },
                "event_source_status": {
                    "description": "Connectivity state for the active event source.",
                    "type": "string",
                    "enum": [
                        "connected",
                        "disconnected",
                        "not_configured"
                    ]
                },
                "event_source_type": {
                    "description": "Active blockchain ingestion source.",
                    "type": "string",
                    "enum": [
                        "websocket",
                        "http",
                        "not_configured"
                    ]
                },
                "parser": {
                    "description": "Parser checkpoint and recovery snapshot.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.ParserHealthResponse"
                        }
                    ]
                },
                "status": {
                    "description": "Overall service status after merging database, TON Center, and parser state.",
                    "type": "string",
                    "enum": [
                        "healthy",
                        "degraded",
                        "unhealthy"
                    ]
                },
                "timestamp": {
                    "description": "Response timestamp in RFC3339 format.",
                    "type": "string"
                },
                "ton_center_api": {
                    "description": "TON Center client/circuit-breaker state.",
                    "type": "string",
                    "enum": [
                        "connected",
                        "recovering",
                        "circuit_breaker_open",
                        "not_configured"
                    ]
                }
            }
        },
        "rest.ListReservationsResponse": {
            "type": "object",
            "properties": {
                "reservations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.ReservationResponse"
                    }
                }
            }
        },
        "rest.ParserHealthResponse": {
            "type": "object",
            "properties": {
                "checkpoint_updated_at": {
                    "description": "Last persisted checkpoint update time in RFC3339 format.",
                    "type": "string"
                },
                "current_source_type": {
                    "description": "Event source currently reflected by parser health.",
                    "type": "string",
                    "enum": [
                        "websocket",
                        "http",
                        "not_configured"
                    ]
                },
                "fallback_count": {
                    "description": "Number of source fallback activations recorded in sync state.",
                    "type": "integer"
                },
                "last_fallback_at": {
                    "description": "Most recent fallback activation time in RFC3339 format.",
                    "type": "string"
                },
                "last_processed_lt": {
                    "description": "Most recent successfully processed TON logical time.",
                    "type": "string"
                },
                "recovery_status": {
                    "description": "Recovery mode derived from live and persisted sync state.",
                    "type": "string",
                    "enum": [
                        "live",
                        "fallback_active",
                        "recovering",
                        "stalled",
                        "not_configured"
                    ]
                },
                "status": {
                    "description": "Parser-specific health state.",
                    "type": "string",
                    "enum": [
                        "healthy",
                        "degraded",
                        "unhealthy"
                    ]
                }
            }
        },
        "rest.Reservation": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "game_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "rest.ReservationResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "game_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "rest.ReserveGameResponse": {
            "type": "object",
            "properties": {
                "reservation": {
                    "$ref": "#/definitions/rest.ReservationResponse"
                }
            }
        },
        "rest.ReserveRequest": {
            "type": "object",
            "required": [
                "wallet_address"
            ],
            "properties": {
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "rest.RevealReservationEnvelope": {
            "type": "object",
            "properties": {
                "reservation": {
                    "$ref": "#/definitions/rest.RevealReservationResponse"
                }
            }
        },
        "rest.RevealReservationListResponse": {
            "type": "object",
            "properties": {
                "reservations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.RevealReservationResponse"
                    }
                }
            }
        },
        "rest.RevealReservationResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "game_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "rest.RevealReserveBatchRequest": {
            "type": "object",
            "required": [
                "game_ids",
                "wallet_address"
            ],
            "properties": {
                "game_ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "rest.RevealReserveRequest": {
            "type": "object",
            "required": [
                "wallet_address"
            ],
            "properties": {
                "wallet_address": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "TelegramAuth": {
            "description": "Telegram Mini App authentication via initData string",
            "type": "apiKey",
            "name": "X-Telegram-Init-Data",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8090",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "POD Game Backend API",
	Description:      "Backend service for TON blockchain gambling game with real-time WebSocket updates",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
